# Generated by Django 4.1.2 on 2022-10-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_tag_options_rename_color_code_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
